// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © hazely8

//@version=5
strategy("超級趨勢回測", overlay = true, margin_long = 100, margin_short = 100)

//supertrend條件
atrPeriod = input(9, "ATR Period")
factor = input.float(3.9, "ATR Multiplier", step = 0.01)

[supertrend, direction] = ta.supertrend(factor, atrPeriod)
plot(direction < 0 ? supertrend : na, "Up direction", color = color.green, style=plot.style_linebr)
plot(direction > 0 ? supertrend : na, "Down direction", color = color.red, style=plot.style_linebr)

//A-V2.2條件
a_v2 = input.bool(true, "Trend Indicator A-V2.2")
ma_period = input.int(52, "MA Period (Length)", minval = 1)
ma_period_smoothing = input.int(10, "MA Period smoothing (Length)", minval=1)

o = ta.ema(open, ma_period)
c = ta.ema(close, ma_period)
h = ta.ema(high, ma_period)
l = ta.ema(low, ma_period)

ha = ticker.heikinashi(syminfo.tickerid)
ha_o = request.security(ha, timeframe.period, o)
ha_c = request.security(ha, timeframe.period, c)
ha_h = request.security(ha, timeframe.period, h)
ha_l = request.security(ha, timeframe.period, l)

ha_o_smooth = ta.ema(ha_o, ma_period_smoothing)
ha_c_smooth = ta.ema(ha_c, ma_period_smoothing)
ha_h_smooth = ta.ema(ha_h, ma_period_smoothing)
ha_l_smooth = ta.ema(ha_l, ma_period_smoothing)

trend = ha_c_smooth >= ha_o_smooth

color_positive = color.new(#26A69A, 50)
color_negative = color.new(#EF5350, 50)
color_hl = color.new(#808080, 80)

color_trend = trend ? color_positive : color_negative

color_show_line_positive = color_positive 
color_show_line_negative = color_negative

color_show_hl_cloud = color_hl
color_show_oc_cloud = color_trend

o_line = plot(ha_o_smooth, color = na, title = "Open line")
c_line = plot(ha_c_smooth, color = na, title = "Close line")

h_line = plot(ha_h_smooth, color = color.white, title = "High line")
l_line = plot(ha_l_smooth, color = color.white, title = "Low line")

fill(o_line, c_line, color=color_show_oc_cloud, title="Open & Close Trendcloud")
fill(h_line, l_line, color=color_show_hl_cloud, title="High & Low Trendcloud")

//QQE MOD條件
QQE_MOD = input.bool(true, "QQE MOD")
RSI_Period = input(6, title='RSI Length')
SF = input(5, title='RSI Smoothing')
QQE = input(3, title='Fast QQE Factor')
ThreshHold = input(3, title="Thresh-hold")
//

src = input(close, title="RSI Source")
//

//
Wilders_Period = RSI_Period * 2 - 1

Rsi = ta.rsi(src, RSI_Period)
RsiMa = ta.ema(Rsi, SF)
AtrRsi = math.abs(RsiMa[1] - RsiMa)
MaAtrRsi = ta.ema(AtrRsi, Wilders_Period)
dar = ta.ema(MaAtrRsi, Wilders_Period) * QQE

longband = 0.0
shortband = 0.0
trend_QQE_MOD = 0

DeltaFastAtrRsi = dar
RSIndex = RsiMa
newshortband = RSIndex + DeltaFastAtrRsi
newlongband = RSIndex - DeltaFastAtrRsi
longband := RSIndex[1] > longband[1] and RSIndex > longband[1] ? 
   math.max(longband[1], newlongband) : newlongband
shortband := RSIndex[1] < shortband[1] and RSIndex < shortband[1] ? 
   math.min(shortband[1], newshortband) : newshortband
cross_1 = ta.cross(longband[1], RSIndex)
trend_QQE_MOD := ta.cross(RSIndex, shortband[1]) ? 1 : cross_1 ? -1 : nz(trend_QQE_MOD[1], 1)
FastAtrRsiTL = trend_QQE_MOD == 1 ? longband : shortband
////////////////////

length = input.int(50, minval=1, title="Bollinger Length")
mult = input.float(0.35, minval=0.001, maxval=5, step=0.1, title="BB Multiplier")
basis = ta.sma(FastAtrRsiTL - 50, length)
dev = mult * ta.stdev(FastAtrRsiTL - 50, length)
upper = basis + dev
lower = basis - dev
color_bar = RsiMa - 50 > upper ? #00c3ff : RsiMa - 50 < lower ? #ff0062 : color.gray

//
// Zero cross
QQEzlong = 0
QQEzlong := nz(QQEzlong[1])
QQEzshort = 0
QQEzshort := nz(QQEzshort[1])
QQEzlong := RSIndex >= 50 ? QQEzlong + 1 : 0
QQEzshort := RSIndex < 50 ? QQEzshort + 1 : 0
//  

Zero = hline(0, color=color.white, linestyle=hline.style_dotted, linewidth=1)

////////////////////////////////////////////////////////////////

RSI_Period2 = input(6, title='RSI Length')
SF2 = input(5, title='RSI Smoothing')
QQE2 = input(1.61, title='Fast QQE2 Factor')
ThreshHold2 = input(3, title="Thresh-hold")

src2 = input(close, title="RSI Source")
//

//
Wilders_Period2 = RSI_Period2 * 2 - 1

Rsi2 = ta.rsi(src2, RSI_Period2)
RsiMa2 = ta.ema(Rsi2, SF2)
AtrRsi2 = math.abs(RsiMa2[1] - RsiMa2)
MaAtrRsi2 = ta.ema(AtrRsi2, Wilders_Period2)
dar2 = ta.ema(MaAtrRsi2, Wilders_Period2) * QQE2
longband2 = 0.0
shortband2 = 0.0
trend_QQE_MOD2 = 0

DeltaFastAtrRsi2 = dar2
RSIndex2 = RsiMa2
newshortband2 = RSIndex2 + DeltaFastAtrRsi2
newlongband2 = RSIndex2 - DeltaFastAtrRsi2
longband2 := RSIndex2[1] > longband2[1] and RSIndex2 > longband2[1] ? 
   math.max(longband2[1], newlongband2) : newlongband2
shortband2 := RSIndex2[1] < shortband2[1] and RSIndex2 < shortband2[1] ? 
   math.min(shortband2[1], newshortband2) : newshortband2
cross_2 = ta.cross(longband2[1], RSIndex2)
trend_QQE_MOD2 := ta.cross(RSIndex2, shortband2[1]) ? 1 : cross_2 ? -1 : nz(trend_QQE_MOD2[1], 1)
FastAtrRsi2TL = trend_QQE_MOD2 == 1 ? longband2 : shortband2

//
// Zero cross
QQE2zlong = 0
QQE2zlong := nz(QQE2zlong[1])
QQE2zshort = 0
QQE2zshort := nz(QQE2zshort[1])
QQE2zlong := RSIndex2 >= 50 ? QQE2zlong + 1 : 0
QQE2zshort := RSIndex2 < 50 ? QQE2zshort + 1 : 0
//  

hcolor2 = RsiMa2 - 50 > ThreshHold2 ? color.silver :
   RsiMa2 - 50 < 0 - ThreshHold2 ? color.silver : na
//plot(FastAtrRsi2TL - 50, title='QQE Line', color=color.white, linewidth=2)
//plot(RsiMa2 - 50, color=hcolor2, title='Histo2', style=plot.style_columns)

Greenbar1 = RsiMa2 - 50 > ThreshHold2
Greenbar2 = RsiMa - 50 > upper

Redbar1 = RsiMa2 - 50 < 0 - ThreshHold2
Redbar2 = RsiMa - 50 < lower
//plot(Greenbar1 and Greenbar2 == 1 ? RsiMa2 - 50 : na, title="QQE Up", style=plot.style_columns, color=#00c3ff)
//plot(Redbar1 and Redbar2 == 1 ? RsiMa2 - 50 : na, title="QQE Down", style=plot.style_columns, color=#ff0062)

bgcolor((Greenbar1 and Greenbar2 == 1) and QQE_MOD ? color.rgb(76, 175, 79, 80) : na)
bgcolor((Redbar1 and Redbar2 == 1) and QQE_MOD ? color.rgb(255, 82, 82, 80) : na)

//交易條件
if direction < 0 and trend and (Greenbar1 and Greenbar2 == 1)
    strategy.entry("Long", strategy.long)
if direction > 0 and not trend and (Redbar1 and Redbar2 == 1)
    strategy.entry("Short", strategy.short)

if close < ha_l_smooth and a_v2
    strategy.close("Long", qty_percent = 100)
if close > ha_h_smooth and a_v2
    strategy.close("Short", qty_percent = 100)